language: java

env:
  global:
    - CC_TEST_REPORTER_ID=f4cad78464edd110ce856555a4dec1c70e1ea7002a299d3490859fae059ecbfe
    
before_install:
  - sudo apt-get install -y python-apsw
  - sudo pip install requests NumPy SciPy scikit-learn titus

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script: mvn clean install -DskipTests=false

after_script:
  - ./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml
  - ./cc-test-reporter upload-coverage -d
