version: '2'

services:
  master:
    build: .
    hostname: master
    volumes:
      - ./exareme-distribution/target/exareme:/root/exareme:ro
    ports:
      - "9090:9090"
    working_dir: /root/exareme/
    entrypoint: /bin/bash -c './bin/exareme-admin.sh --start --local;tail -f /tmp/exareme/var/log/exareme-master.log;'

  worker:
    build: .
    volumes:
      - ./exareme-distribution/target/exareme:/root/exareme:ro
    working_dir: /root/exareme/
    entrypoint: /bin/bash -c 'sleep 5;./bin/exareme-admin.sh --start  --local;tail -f /tmp/exareme/var/log/exareme-worker.log;'
    environment:
      - EXAREME_MASTER=master
