version: '2'

services:
  exalocal:
    image: hbpmip/exaremelocal
    links:
      - rawdb
    environment:
      - MASTER_FLAG=master
    ports:
      - "9090:9090"

  rawdb:
    hostname: rawdb
    image: raw-sniffer
    volumes:
      - ../rawdb_datasets:/datasets:ro
    ports:
      - "54321:54321"
      - "5555:5555"
