version: '3.2'

networks:
  net-federation:
    external:
      name: mip-federation

services:
  mip-portainer:
    image: ${PORTAINER_IMAGE}
    command:
      --ssl
      --sslcert /certs/live/${DOMAIN_NAME}/cert.pem
      --sslkey /certs/live/${DOMAIN_NAME}/privkey.pem
    deploy:
      placement:
        constraints:
          - node.role == manager       # Ensures we only start on manager nodes
          - node.labels.name == ${FEDERATION_NODE}
    networks:
      - "net-federation" # Connect the docker container to the global network
    ports:
      - '9000:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${HOME_PATH}portainer:/data'
      - '/etc/letsencrypt/live/${DOMAIN_NAME}:/certs/live/${DOMAIN_NAME}:ro'
      - '/etc/letsencrypt/archive/${DOMAIN_NAME}:/certs/archive/${DOMAIN_NAME}:ro'

