---
- name: Find Leader
  shell: docker node ls -f "role=manager" --format '{{ "{{" }}.Hostname {{ "}}" }}'
  register: leader
  tags:
    - always

#Todo if we have multiple masters and maybe leader.stdout -> leader.stdout_lines with_items?
- name: Run Exareme Master
  shell: docker stack deploy -c docker-compose-master.yml {{ leader.stdout }}
  args:
    chdir: "{{ home_path }}Compose-Files/"
  environment:
    FEDERATION_NODE: "{{ leader.stdout }}"
    FEDERATION_ROLE: "master"
    EXAREME_IMAGE: "{{ EXAREME_IMAGE }}:{{ EXAREME_TAG }}"
    EXAREME_KEYSTORE: "{{ EXAREME_KEYSTORE }}"
    DOCKER_DATA_FOLDER: "{{ DOCKER_DATA_FOLDER }}"
    LOCAL_DATA_FOLDER: "{{ data_path }}"
  tags:
    - exareme

- name: Portainer folder
  shell: >
         test -d {{ PORTAINER_DATA }}
         || mkdir -p {{ PORTAINER_DATA }}
         || ( echo Failed to create {{ PORTAINER_DATA }}; exit 1 )
  environment:
    PORTAINER_DATA: "{{ PORTAINER_DATA }}"

- name: Find Portainer service ID if exists
  shell: docker service inspect -f '{{ "{{" }}.ID{{ "}}" }}' {{ PORTAINER_NAME }}
  register: portainerID
  ignore_errors: true
  tags:
    - portainer

- name: Remove Portainer service is exists
  shell: docker service rm {{ portainerID.stdout }}
  register: portainer_rm
  ignore_errors: true
  tags:
    - portainer

- name: Run Portainer Service
  shell: >
    sudo docker service create \
    --publish mode=host,target={{ PORTAINER_PORT }},published=9000 \
    --constraint 'node.role == manager' \
    --detach=true --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    --mount type=bind,src={{ PORTAINER_DATA }},dst=/data \
    --mount type=bind,src=/etc/letsencrypt/live/{{ DOMAIN_NAME }},dst=/certs/live/{{ DOMAIN_NAME }} \
    --mount type=bind,src=/etc/letsencrypt/archive/{{ DOMAIN_NAME }},dst=/certs/archive/{{ DOMAIN_NAME }} \
    --name {{ PORTAINER_NAME }} {{PORTAINER_IMAGE }}{{ PORTAINER_VERSION }} \
    --ssl --sslcert /certs/live/{{ DOMAIN_NAME }}/cert.pem --sslkey /certs/live/{{ DOMAIN_NAME }}/privkey.pem
  environment:
    PORTAINER_IMAGE: "{{ PORTAINER_IMAGE }}{{ PORTAINER_VERSION }}"
    PORTAINER_NAME: "{{ PORTAINER_NAME }}"
    PORTAINER_DATA: "{{ PORTAINER_DATA }}"
    DOMAIN_NAME: "{{ DOMAIN_NAME }}"
  tags:
    - portainer

- name: Run Exareme Workers
  shell: docker stack deploy -c docker-compose-worker.yml {{ hostvars[item]['hostname'] }}
  args:
    chdir: "{{ home_path }}Compose-Files/"
  environment:
    FEDERATION_NODE: "{{ hostvars[item]['hostname'] }}"
    EXAREME_IMAGE: "{{ EXAREME_IMAGE }}:{{ EXAREME_TAG }}"
    EXAREME_KEYSTORE: "{{ EXAREME_KEYSTORE }}"
    DOCKER_DATA_FOLDER: "{{ DOCKER_DATA_FOLDER }}"
    LOCAL_DATA_FOLDER: "{{ hostvars[item]['data_path'] }}"
  with_items: "{{ groups['workers'] }}"
  ignore_errors: true
  tags:
    - exareme
