---
- name: Find Leader
  shell: docker node ls -f "role=manager" --format '{{ "{{" }}.Hostname {{ "}}" }}'
  register: leader
  tags:
    - always
    -
- name: Find Exareme ID
  shell: docker service ls --filter name={{ leader.stdout }}_exareme-master --format '{{ "{{" }}.ID{{ "}}" }}'
  register: exaremeService
  tags:
    - exareme

- name: Remove Exareme Service
  shell:  docker service rm "{{ exaremeService.stdout }}"
  tags:
    - exareme

- name: Find Portainer ID
  shell: docker service ls --filter name={{ leader.stdout }}_mip-portainer --format '{{ "{{" }}.ID{{ "}}" }}'
  register: portainer_id
  ignore_errors: true
  tags:
    - portainer

- name: Remove Portainer ID
  shell: docker service rm "{{ portainer_id.stdout }}"
  register: portainer_rm
  ignore_errors: true
  tags:
    - portainer
