---
- name: Find Leader
  shell: docker node ls -f "role=manager" --format '{{ "{{" }}.Hostname {{ "}}" }}'
  register: leader
  tags:
    - always

- name: Find Stacks
  shell: docker stack ls --format '{{ "{{" }}.Name{{ "}}" }}'
  register: nodeStacks
  tags:
    - exareme

- name: Find Exareme master service
  shell: docker service ls --filter name={{ leader.stdout }}_exareme-master --format '{{ "{{" }}.ID{{ "}}" }}'
  register: master
  tags:
    - exareme

- name: Remove Exareme master
  shell: docker service rm "{{ master.stdout }}"
  register: master_rm
  ignore_errors: true
  tags:
    - exareme

- name: Remove Exareme Workers
  shell: docker service rm "{{ item }}"_exareme
  with_items:
    - "{{ nodeStacks.stdout_lines }}"
  register: workers_rm
  ignore_errors: true
  tags:
    - exareme

- name: Find Portainer ID
  shell: docker service ls --filter name={{ leader.stdout }}_mip-portainer --format '{{ "{{" }}.ID{{ "}}" }}'
  register: portainer_id
  ignore_errors: true
  tags:
    - portainer

- name: Remove Portainer ID
  shell: docker service rm "{{ portainer_id.stdout }}"
  register: portainer_rm
  ignore_errors: true
  tags:
    - portainer
