---
- name: Find Leader
  shell: docker node ls -f "role=manager" --format '{{ "{{" }}.Hostname {{ "}}" }}'
  register: leader
  tags:
    - always

- name: Find Stacks
  shell: docker stack ls --format '{{ "{{" }}.Name{{ "}}" }}'
  register: nodeStacks
  tags:
    - exareme

- name: Remove Exareme stacks
  shell: docker stack rm "{{ item }}"
  with_items:
    - "{{ nodeStacks.stdout_lines }}"
  when: item != "{{ leader.stdout }}_portainer"
  ignore_errors: true
  tags:
    - exareme

- name: Remove Portainer
  shell: docker stack rm "{{ item }}"
  with_items:
    - "{{ nodeStacks.stdout_lines }}"
  when: item == "{{ leader.stdout }}_portainer"
  register: portainer_rm
  ignore_errors: true
  tags:
    - portainer
