---
- hosts: manager
  name: Initialize Docker Swarm
  remote_user: "{{ REMOTE_USER }}"
  become: yes
  become_user: "{{ BECOME_USER }}"
  roles:
   - swarm-init

- hosts: manager
  name: Add Label In Nodes Of Swarm
  remote_user: "{{ REMOTE_USER }}"
  become: yes
  become_user: "{{ BECOME_USER }}"
  roles:
   - add-labels

- hosts: manager
  name: Copy Folder Containing The docker-compose Files
  remote_user: "{{ REMOTE_USER }}"
  become: yes
  become_user: "{{ BECOME_USER }}"
  roles:
   - copy-directory