# Exareme Tag
EXAREME_TAG: "final"
# Exareme Image
EXAREME_IMAGE: "sofiakar/myexareme"



## Nothing to change here  ##

# Key-Value Store
EXAREME_KEYSTORE: "exareme-keystore:8500"
# Exareme db
DOCKER_DATA_FOLDER: "/root/exareme/datasets/"

# Portainer
PORTAINER_PORT: "9000"
PORTAINER_IMAGE: "portainer/portainer"
PORTAINER_VERSION: ":latest"
PORTAINER_DATA: "{{hostvars['master']['home_path']}}portainer"







